//! Kitchen sink: every optional knob `tinkr_framework` offers.
//!
//! Shows, on top of what `quickstart` covers:
//!
//! - merging a pre-built [`Router`] with `.router(...)`
//! - mixing in single routes with `.route(...)`
//! - registering gRPC services with `.grpc_service(...)`
//! - gRPC server reflection with `.grpc_reflection(...)`
//! - customizing the built-in `/health` endpoint with `.health(...)`,
//!   including consumer-defined statuses
//! - a graceful-shutdown clean-up hook with `.on_shutdown(...)`
//! - serving multiple addresses with `.bind(...)`
//! - custom telemetry: a metric through the OpenTelemetry global meter and
//!   a child span through `tracing` (exported when an OTLP endpoint is
//!   configured, e.g. `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317`)
//!
//! Configuration loading has its own example (`examples/config.rs`); the
//! shutdown grace period and the default port come from the configuration.
//!
//! Run with:
//!
//! ```sh
//! cargo run -p demo --example kitchen_sink
//! ```
//!
//! Then, in another shell (the same routes are also served on the extra
//! loopback bind, 127.0.0.1:9090):
//!
//! ```sh
//! curl http://127.0.0.1:8080/health            # -> {"service":"demo",...,"checks":[...]}
//! curl http://127.0.0.1:8080/api/hello         # -> hello from the merged router
//! curl http://127.0.0.1:9090/api/version       # -> demo 0.0.0
//! grpcurl -plaintext 127.0.0.1:8080 list       # -> hello.Greeter (via reflection)
//! grpcurl -plaintext -d '{"name":"world"}' \
//!     127.0.0.1:8080 hello.Greeter/SayHello     # -> {"message":"Hello world!"}
//! ```
//!
//! Press ctrl-c (or send SIGTERM) to shut down gracefully: in-flight requests
//! drain first, then the `.on_shutdown(...)` hook runs before the process
//! exits.

use std::time::Instant;

use demo::MyGreeter;
use demo::pb::greeter_server::GreeterServer;
use tinkr_framework::health::{Check, Health, Status};
use tinkr_framework::routing::get;
use tinkr_framework::{Router, Server};

// The standard statuses (`Status::OK`, `DEGRADED`, `ERROR`) can be extended
// with your own. The bool says whether `/health` should still answer 200.
const READ_ONLY: Status = Status::new("read_only", true);

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Load .env + configuration and set up RUST_LOG-filtered logging. Call
    // exactly once, before building any Server.
    let cfg = tinkr_framework::init!()?;

    // Metrics record through the OpenTelemetry global meter (use the
    // framework's `opentelemetry` re-export) and flow to the configured
    // OTLP endpoint; without one they cost nothing.
    let hellos = tinkr_framework::opentelemetry::global::meter("demo")
        .u64_counter("demo.hello.requests")
        .build();

    // A pre-built Router. Build these anywhere (other modules, other
    // crates) and merge them in whole with `.router(...)`.
    let api = Router::new()
        .route(
            "/api/hello",
            get(move || {
                let hellos = hellos.clone();
                async move {
                    hellos.add(1, &[]);
                    // Child spans nest under the framework's per-request
                    // span, sharing its trace.
                    let _span = tracing::info_span!("compose_greeting").entered();
                    "hello from the merged router"
                }
            }),
        )
        .route("/api/version", get(|| async { "demo 0.0.0" }));

    Server::new()
        // Merge a whole router...
        .router(api)
        // ...and/or add individual routes; both styles compose freely.
        .route("/api/echo", get(|| async { "echo" }))
        // Repeat `.grpc_service(...)` for each gRPC service you have.
        .grpc_service(GreeterServer::new(MyGreeter))
        // Optional: serve gRPC reflection so clients like grpcurl can
        // discover the services above. The descriptor set constant is
        // generated by buf's `file_descriptor_set` option (see buf.gen.yaml).
        .grpc_reflection(demo::pb::FILE_DESCRIPTOR_SET)
        // Optional: customize the built-in `/health` endpoint. The function
        // returns the overall status plus the checks it was derived from.
        .health(|| async {
            let start = Instant::now();
            let database = ping_database().await;

            let db_check = Check {
                name: "database".into(),
                status: if database.is_ok() {
                    Status::OK
                } else {
                    Status::ERROR
                },
                message: database.err(),
                duration: start.elapsed(),
            };

            // Derive the overall status however makes sense for the service;
            // here we can still serve reads from cache without the database.
            let overall = if db_check.status == Status::ERROR {
                READ_ONLY
            } else {
                Status::OK
            };

            Health {
                status: overall,
                checks: vec![db_check],
            }
        })
        // Optional: runs after graceful shutdown completes, right before
        // `serve()` returns. Close database pools, flush buffers, etc. here;
        // draining + this hook share the configured `shutdown_timeout`.
        .on_shutdown(async { tracing::info!("shutting down, running clean-up") })
        // Optional: without any `.bind(...)` calls, `serve()` listens on the
        // configured port on all IPv4 + IPv6 addresses. Explicit binds
        // replace that default...
        .bind("127.0.0.1:9090")
        // ...so re-add the configured port if you still want it. `bind()`
        // accepts ports, IPs, strings, socket addresses, and pre-bound
        // listeners; see the `Server::bind` docs.
        .bind(cfg.port)
        .serve()
        .await?;

    Ok(())
}

/// Stand-in for a real dependency probe.
async fn ping_database() -> Result<(), String> {
    Ok(())
}
